name: ViaChatFixer
version: ${project.version}
author: MrMicky
description: Allow 1.11+ players to have longer chat messages on 1.8-1.10 servers with ViaVersion
softdepend: [ViaVersion]
load: STARTUP
main: fr.mrmicky.viachatfixer.bukkit.ViaChatFixerBukkit